# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0befd9f508784512540bc93cc4609dde0399ede01d4027bdae5cfaaa4af1c2a26dc1147b8a4b29cea26827ef4ee41b26f602f77391df6c041319fa2d723e9390

test:
  secret_key_base: c528efcdcfaffdf1eaa5ad79f23e747c8533d2b3be4011e1c623a2a46735d12db0e5f8abb044cee4b3bbac7cef64616769e1ac97d82c43fdb4812be916bc84fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
